version: '3.2'
services:
    changedetection:
      image: filelist-api-whitelist
      container_name: filelist-api
      environment:
        FL_USERNAME: /run/secrets/fl_username
        FL_PASSWORD: /run/secrets/fl_password
      secrets:
        - fl_username
        - fl_password
      restart: unless-stopped
secrets:
  fl_username:
    file: ./username
  fl_password:
    file: ./password
