version: '3.2'
services:
    changedetection:
      image: filelist-api-whitelist
      container_name: filelist-api
      environment:
        - FL_USERNAME=YOUR_USER
        - FL_PASSWORD=YOUR_PASSWORD
      restart: unless-stopped
